config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "foods#home"
  get "/about", to: "foods#about"
  get "/foods", to: "foods#index", as: "foods"
  get "/foods/show/:id", to: "foods#show", as: "foods_show"
  get "/foods/new", to: "foods#new", as: "list_new_food"
  post "/foods", to: "foods#create"
  get "/foods/edit/:id", to: "foods#edit", as: "list_edit_food"
  patch "/foods/show/:id", to: "foods#update"
  delete "/foods/:id", to: "foods#destroy", as: "destroy_listed_food"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
    validates :food_title,:anime_name,:anime_food_recipe, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_action :foods_show_all, only: [:home, :index]
  before_action :foods_get_id, only: [:show, :edit, :update, :destroy]

  def home
  end

  def about
  end

  def index
  end

  def show
    @foods = Food.find(params[:id])
  end

  def new
    @foods = Food.new
  end

  def create
    @foods = Food.new(food_params)

    if @foods.save
      redirect_to foods_path, notice: 'Anime Food was successfully created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @foods.update(food_params)
      redirect_to foods_show_path, notice: 'Anime Food was successfully edited'
    else
      render :edit
    end
  end

  def destroy
    redirect_to foods_path if @foods.destroy
  end

  private

  def foods_show_all
    @foods =  Food.all.order(created_at: :asc)
  end

  def foods_get_id
    @foods = Food.find(params[:id])
  end
  
  def food_params
    params.require(:food).permit(:food_title, :anime_name, :anime_food_recipe)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/assets/_about.html.erb
<section class="section "><div class="container">
<div class="content has-text-centered is-medium pb-6">
<div class="columns is-centered">
<div class="column is-7">
  <h1><strong>About &#129299;</strong></h1>
  <p>A list of a few delicious meals from anime that you should definitely try. Whether you’re looking for something simple or something fancy and complicated, all of these dishes are great ways to start your meal out right! Discover the best anime food and drink on the internet! Anime food is one of the most popular blog posts on Website and it is also highly rated. This anime food blog post has been viewed by many people and liked by them much. We hope you will like this website and thank you for browsing our site. If you like anime food, then The Food Blog was made for you. We love anime, so we started this blog to share our favorite images and recipes with you! Keep an eye out for our future posts and please subscribe to see new recipes and updates on our website, Facebook or Twitter. You can also sign up for email updates to get notified when our posts are published.</p>
</div>
</div>
</div>
</div>
</section>

app/views/assets/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered has-text-white">
    <p>
      <strong class="has-text-white">Ghibli Food Blog</strong> by <a>Vincent Larisma</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

app/views/assets/_navbar.html.erb
<nav class="navbar has-shadow is-white" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a href="/"class="navbar-item title"><img src="https://www.pngmart.com/files/Anime-Food-PNG-Free-Download.png" alt="logo" style="max-height: 70px;" class="p-2"> Ghibli Food Blog </a>
  </div>
  <div class="navbar-menu">
  <div class="navbar-end">
  
  <a href="/about" class="navbar-item">About</a>
  <%= link_to "Add New Recipe", list_new_food_path, class: "navbar-item" %>
  <a href="/foods" class="navbar-item">All Anime Recipes</a>
  <a href="https://github.com/vincent-larisma/anime_food_blog" target="_blank" class="navbar-item">Check Out Source Code</a>
 
  </div>
  </div>
</nav>

app/views/assets/_sample_recipes.html.erb
<section class="section section-background-color">
<div class="content has-text-centered is-medium mb-6">
<h1><strong>&#10024; Anime Food Recipe &#10024;</strong></h1>
</div>

<div class="container pb-6">
<div class="columns">
<% @foods[0...2].each do |card_item| %>
<div class="column">
<div class="card">
  <div class="card-content">
    <p class="title">
      <%=  card_item.food_title%>
    </p>
    <p class="subtitle">
     Anime: <%= card_item.anime_name %>
    </p>
<div class="content">
<p>
<%= card_item.anime_food_recipe.length > 10 ? card_item.anime_food_recipe[0...1000] + "..." : card_item.anime_food_recipe %>
</p>
    <p class="has-text-centered">
     *click show to know about the recipe*
    </p>
    </div>
  </div>
  <div class="card-footer">
  <a class="has-text-black card-footer-item" href="/foods/show/<%= card_item.id %>">
    <i class="fa-regular fa-eye"></i>-SHOW 
    
  </a>
</div>
</div>
</div>
<% end %>
</div>
</div>

</section>

app/views/foods/_form.html.erb
<%= form_with model: @foods, html: { class: "field" }, url: {action: action} do |form| %>
  
  <%= form.label "Food Title", class: "label is-medium"  %>

  <div class="control">
  <%= form.text_field :food_title, class: "input is-medium" %>
  </div>
    <% @foods.errors.full_messages_for(:food_title).each do |message| %>
    <div class="notification is-danger"><%= message %></div>
  <% end %>
  <%= form.label "Anime from?", class: "label is-medium"  %>
  
  <div class="control">
  <%= form.text_field :anime_name, class: "input is-medium" %>
   <% @foods.errors.full_messages_for(:anime_name).each do |message| %>
    <div class="notification is-danger"><%= message %></div>
  <% end %>
  </div>
  <%= form.label "Anime Food Recipe", class: "label is-medium" %>
  <div class="control">
  <%= form.text_area :anime_food_recipe, class: "textarea" %>
    <% @foods.errors.full_messages_for(:anime_food_recipe).each do |message| %>
    <div class="notification is-danger"><%= message %></div>
  <% end %>
  </div>
 <div class="field"><p class="control">
  <%= form.submit "Submit", class: "button is-primary mt-4 is-medium" %>
 </p></div>


<% end %>

app/views/foods/about.html.erb
<section class="section "><div class="container">
<div class="content has-text-centered is-large pb-6">
<div class="columns is-centered">
<div class="column is-8">
  <h1><strong>About &#129299;</strong></h1>
  <p>A list of a few delicious meals from anime that you should definitely try. Whether you’re looking for something simple or something fancy and complicated, all of these dishes are great ways to start your meal out right! Discover the best anime food and drink on the internet! Anime food is one of the most popular blog posts on Website and it is also highly rated. This anime food blog post has been viewed by many people and liked by them much. We hope you will like this website and thank you for browsing our site. If you like anime food, then The Food Blog was made for you. We love anime, so we started this blog to share our favorite images and recipes with you! Keep an eye out for our future posts and please subscribe to see new recipes and updates on our website, Facebook or Twitter. You can also sign up for email updates to get notified when our posts are published.</p> 
  
  <div class="column"><h2>Sample Anime Food Pics &#128523;</h2><figure><%= image_tag "halohalo_anime.jpg" %><%= image_tag "Ponyo-Ramen.png" %><%= image_tag "noodle_anime_food.jpg" %></figure></div>
</div>
</div>
</div>
</div>
</section>

app/views/foods/edit.html.erb
<section class="section"><div class="container">
<h1 class="title">You are now Editing a Food List Item!</h1>

<%= render "form", foods: @foods, action: :update %>

</div></section>

app/views/foods/home.html.erb
<section class="hero is-large hero-image">
  <div class="hero-body">

  <div class="tile is-ancestor">
  
  <div class="tile is-parent is-3 has-text-centered">
  </div>

  <div class="tile is-parent is-6 has-text-centered">
    <div class="tile is-child box">
      <p class="title has-text-white ">An Anime Food Blog</p>
      <p class="subtitle "><strong class="has-text-white"> cooking is an art itself...</strong></p>
    </div>
  </div>

  <div class="tile is-parent is-3 has-text-centered">
  </div>
</div>
  </div>
</section>

<%= render "assets/sample_recipes" %>

<%= render "assets/about" %>

app/views/foods/index.html.erb
<section class="section section-background-color">

<div class="content has-text-centered is-medium mb-6">
<h1><strong>&#10024; Anime Food Recipe List &#10024;</strong></h1>
</div>
<div class="container">
<% @foods.each do |card_item| %>
<div class="columns is-centered m-6">
<div class="column is-half">
<div class="card">
  <div class="card-content">
    <p class="title">
      <%=  card_item.food_title%>
    </p>
    <p class="subtitle">
     Anime: <%= card_item.anime_name %>
    </p>
<div class="content">
<p>
<%= card_item.anime_food_recipe.length > 10 ?  card_item.anime_food_recipe[0...1000] + "..." : card_item.anime_food_recipe %>
</p>
    <p class="has-text-centered">
     *click show to know about the recipe*
    </p>
    </div>
  </div>
  <div class="card-footer">
    <a class="has-text-black card-footer-item" href="/foods/show/<%=card_item.id%>">
    <i class="fa-regular fa-eye"></i>-SHOW 
    </a>
</div>
</div>
</div>
</div>
<% end %>
</div>
</section>

app/views/foods/new.html.erb
<section class="section"><div class="container">
<h1 class="title">Create A New Anime Food Blog Entry!</h1>
<%= render "form", foods: @foods, action: :create %>
</div></section>

app/views/foods/show.html.erb
<section class="section section-background-color">
<%# .anime_food_recipe
.food_title
.anime_name %>
<div class="content has-text-centered is-medium mb-6">
<h1><strong>&#127857; <%= @foods.food_title %> &#127857;</strong></h1>
<h2>Anime From <%= @foods.anime_name %></h2>
</div>  
<div class="container content">
<h2>Recipe :</h2>
<textarea class="column textarea box" readonly><%= @foods.anime_food_recipe %></textarea>
<div class="columns is-centered has-text-centered ">
    <a href="/foods/edit/<%=@foods.id%>" class="column is-1 card button-bigger"><i class="fa-regular fa-pen-to-square"></i>-EDIT</a>
    <div class="column is-0"></div>
    <a data-confirm="ARE YOU SURE?" rel="nofollow" data-method="delete" href="/foods/<%=@foods.id%>" class="column is-1 card button-bigger"><i class="fa-solid fa-trash"></i></i>-DELETE</a>
</div>
</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeFood</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/6914ea1ba2.js" crossorigin="anonymous"></script>
  </head>

  <header>
  <%= render "assets/navbar" %>
  </header>
  <body>
    <%= yield %>
  </body>
  <%= render "assets/footer" %>
</html>